version: '3'
services:
  yonks_python:
    build: .
    container_name: yonks_python
    working_dir: /app
    tty: true
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    command: "uvicorn main:app --reload --host 0.0.0.0 --port 8000"